//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMES.MaterialCal.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\kf")]
        public string kf_path {
            get {
                return ((string)(this["kf_path"]));
            }
            set {
                this["kf_path"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\sf")]
        public string sf_path {
            get {
                return ((string)(this["sf_path"]));
            }
            set {
                this["sf_path"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("e:\\barcode")]
        public string barcode_remotepath {
            get {
                return ((string)(this["barcode_remotepath"]));
            }
            set {
                this["barcode_remotepath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\barcode1")]
        public string barcode_localpath {
            get {
                return ((string)(this["barcode_localpath"]));
            }
            set {
                this["barcode_localpath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\barcode2")]
        public string barcode_localpathbak {
            get {
                return ((string)(this["barcode_localpathbak"]));
            }
            set {
                this["barcode_localpathbak"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string sf_mobile {
            get {
                return ((string)(this["sf_mobile"]));
            }
            set {
                this["sf_mobile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("13995728929;13227503432;13774160723;13995745273")]
        public string ekf_mobile {
            get {
                return ((string)(this["ekf_mobile"]));
            }
            set {
                this["ekf_mobile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string wkf_mobile {
            get {
                return ((string)(this["wkf_mobile"]));
            }
            set {
                this["wkf_mobile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("gao.yuan@dcec.com.cn;chen.dengqing@dcec.com.cn;huang.yong@dcec.com.cn")]
        public string ekf_mail {
            get {
                return ((string)(this["ekf_mail"]));
            }
            set {
                this["ekf_mail"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("zhang.jun01@dcec.com.cn")]
        public string wkf_mail {
            get {
                return ((string)(this["wkf_mail"]));
            }
            set {
                this["wkf_mail"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\sf1\\xml")]
        public string sf_xml_path {
            get {
                return ((string)(this["sf_xml_path"]));
            }
            set {
                this["sf_xml_path"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\sf1\\xml3")]
        public string sf_xml_bak_path {
            get {
                return ((string)(this["sf_xml_bak_path"]));
            }
            set {
                this["sf_xml_bak_path"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\sf1\\txt")]
        public string sf_txt_path {
            get {
                return ((string)(this["sf_txt_path"]));
            }
            set {
                this["sf_txt_path"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\sf1\\txt3")]
        public string sf_txt_bak_path {
            get {
                return ((string)(this["sf_txt_bak_path"]));
            }
            set {
                this["sf_txt_bak_path"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\SM01")]
        public string sf_txt_supply_path {
            get {
                return ((string)(this["sf_txt_supply_path"]));
            }
            set {
                this["sf_txt_supply_path"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\SM03")]
        public string sf_txt_supply_bak_path {
            get {
                return ((string)(this["sf_txt_supply_bak_path"]));
            }
            set {
                this["sf_txt_supply_bak_path"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\192.168.112.144\\sf")]
        public string sf_xml_remote_path {
            get {
                return ((string)(this["sf_xml_remote_path"]));
            }
            set {
                this["sf_xml_remote_path"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\192.168.112.144\\sf")]
        public string sf_txt_remote_path {
            get {
                return ((string)(this["sf_txt_remote_path"]));
            }
            set {
                this["sf_txt_remote_path"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\192.168.112.144\\sf")]
        public string sf_txt_supply_remote_path {
            get {
                return ((string)(this["sf_txt_supply_remote_path"]));
            }
            set {
                this["sf_txt_supply_remote_path"] = value;
            }
        }
    }
}
